# Generated by Django 3.0.5 on 2020-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('dependants', models.IntegerField(default=0)),
                ('applicantIncome', models.IntegerField(default=0)),
                ('coapplicantIncome', models.IntegerField(default=0)),
                ('loanAmount', models.IntegerField(default=0)),
                ('loanTerm', models.IntegerField(default=0)),
                ('creditHistory', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduateEducation', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduated')], max_length=15)),
                ('selfEmployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
